### ISSUE TITLE
cannot import name 'Graph_AMR_Reader'

### ISSUE THREAD

**Issue by esmanning** [ablodge/amr-utils#3]
When trying to use style.py I get:

Traceback (most recent call last):
  File "amr_utils/style.py", line 439, in <module>
    main()
  File "amr_utils/style.py", line 412, in main
    from amr_utils.amr_readers import Graph_AMR_Reader
ImportError: cannot import name 'Graph_AMR_Reader'

Graph_AMR_Reader seems to no longer exist?

**Comment by ablodge** [comment]
Ahh. For now, try `LDC_AMR_Reader` instead.

**Comment by esmanning** [comment]
Ok, thanks! That seems to work as long as I use an aligned version - with unaligned LDC format I got

Traceback (most recent call last):
  File "amr_utils/style.py", line 439, in <module>
    main()
  File "amr_utils/style.py", line 425, in main
    amrs = cr.load(file, verbose=False, remove_wiki=True)
  File "/Users/purplatypus/amr-utils-master/amr_utils/amr_readers.py", line 286, in load
    for align in alignments:
UnboundLocalError: local variable 'alignments' referenced before assignment

**Comment by ablodge** [comment]
I added a class `Graph_AMR_Reader` which is basically a stripped-down version of `LDC_AMR_Reader`. `style.py` works on my side. Tell me if you have any more problems.
